### PR TITLE
Expand launches provided by ILaunchShortcut2

### PR DESCRIPTION
**Pull request by laeubi**
Currently ILaunchShortcut2 is only queried for the launch button but not when one uses the context menu, this adds expanding the items from a ILaunchShortcut2 to be added to the Run As / Debug As / ... menus.

FYI @mickaelistria 
This is related to
- https://github.com/eclipse-m2e/m2e-core/pull/1309

### CODE REVIEW

**Comment by mickaelistria** [comment]
I like the idea overall, however I'm a bit worried that this expands a lot the Run/Debug context menus, sometimes irrelevantly. However, I don't have a clear idea of an example where that would happen; while I can imagine many cases for which this feature would be beneficial.
So I suggest that we merge ASAP, since we're in early stage; so we have plenty of time to gather feedback and maybe improve, maybe revert...

**Comment by laeubi** [comment]
Lets go :+1:

**Comment by mickaelistria** [comment]
Thank you for this contribution!

**Comment by iloveeclipse** [comment]
This caused a severe regression: https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/213
I plan to revert this change pretty soon, as this makes my IDE useless for debugging tests, unless there will be a fix soon.

**Comment by mickaelistria** [comment]
@iloveeclipse I'm looking at this issue with highest priority. I hope in ~20 minutes, I can recommend a patch, or a revert. Is it OK to wait that long?

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.debug/pull/125 is supposed to fix the regression. I'm merging it right now.

**Pull request merged**
