### PR TITLE
Remove org.eclipse.pde.ds.lib/annotations.jar from extra classpath

### PR DESCRIPTION
**Pull request by laeubi**
This is obsolete now

### CODE REVIEW

**Comment by HannesWell** [comment]
There are maybe more locations like these.
PDE-DS siggested multiple patterns to work-around previousTycho limitations. It even issued a warning If None was present.

What do you think about reverting that to encourage Users to remove them now?

**Comment by laeubi** [comment]
> There are maybe more locations like these.

I only found those in platform SDK

> PDE-DS siggested multiple patterns to work-around previousTycho limitations. It even issued a warning If None was present.

Then these "worarounds" should be removed

> What do you think about reverting that to encourage Users to remove them now?

Reverting what? I think the easiest fix is to simply remove the workaround and a failing build is the best to discover such things.

**Comment by HannesWell** [comment]
> > What do you think about reverting that to encourage Users to remove them now?
> 
> Reverting what? I think the easiest fix is to simply remove the workaround and a failing build is the best to discover such things.

The warnings and quick-fixes should be 'reverted' from checking if any is present and suggesting to the them, to check if any is present and suggesting to remove them.

> Then these "worarounds" should be removed
> 

Eventually yes. The question is how long we want to have the 'reverted' check?

**Comment by akurtakov** [comment]
We can keep the "reverted" check without thinking about period right now IMHO.

**Comment by laeubi** [comment]
Remove whatever is useless now ;-)

It has always been a hassle to enable this and that while other tools simply "work" ...

**Pull request merged**
