### PR TITLE
.gitignore /.polyglot.* #128

### PR DESCRIPTION
**Pull request by jukzi**

### CODE REVIEW

**Comment by jukzi** [comment]
see https://github.com/eclipse-platform/.github/issues/128#issuecomment-1576122148

**Comment by laeubi** [comment]
I don't think a project specific git ignore is required here, why not add it to the projects root?

**Comment by jukzi** [comment]
it's just the outcome of the UI's ignore.

**Comment by akurtakov** [comment]
Please make this change in the toplevel .gitignore. That way we wouldn't have to touch bundle versions too.

**Pull request merged**
