### PR TITLE
Register launch prototype as text file content

### PR DESCRIPTION
**Pull request by Bananeweizen**
The compare editor opens a binary comparison by default for .prototype files (those are launch configuration prototypes). Have a content type and text file type registration to have the text comparison opening by default.

grafik

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Thanks

**Comment by SarikaSinha** [comment]
@Bananeweizen Can you add this to N&N ?

**Comment by iloveeclipse** [comment]
> @Bananeweizen Can you add this to N&N ?

Do you think it is worth to add a N&N for a bugfix?

**Comment by SarikaSinha** [comment]
> > @Bananeweizen Can you add this to N&N ?
> 
> Do you think it is worth to add a N&N for a bugfix?

I think many would not have know this method to use the prototype.

**Comment by Bananeweizen** [comment]
Since you automatically get this by first creating a prototype in the UI, and then selecting the "save as shared" option from the commons tab, I also don't feel this is worth an entry in new and noteworthy. Basically it all depends on whether you use prototypes _at all_, and that was covered by previous N&N.

**Pull request merged**
