### PR TITLE
Terminate functionality in run toolbar

### PR DESCRIPTION
**Pull request by vudayani**
Add the Terminate button functionality in the run toolbar
- Shows a dropdown of running processes and terminates the process when selected
- Terminate All option in the dropdown - terminates all the running processes

### CODE REVIEW

**Comment by mickaelistria** [comment]
I don't think it should be shown by default as the Debug view provides a good UI for that case.

**Comment by jukzi** [comment]
> I don't think it should be shown by default as the Debug view provides a good UI for that case.

no?! i requested that feature because there is NO (working) "terminate all" button in eclipse

**Comment by mickaelistria** [comment]
>  NO (working) "terminate all" button in eclipse

So it would probably be better to add on in the Debug view.

**Comment by jukzi** [comment]
This PR is meant to target https://bugs.eclipse.org/bugs/show_bug.cgi?id=578877 right?

**Comment by iloveeclipse** [comment]
I would propose to not add this to the global toolbar, but to the "Launch configurations" view, where it would have a much better fit. See screenshot:

image

**Comment by laeubi** [comment]
@iloveeclipse if you open the console view you should see the terminate button at the "Shouldn't it be here" location (for terminating the current process attached to the console). But I don't know if such a toolbar could be applied to *all* views in a PartStack.

**Comment by jukzi** [comment]
> @iloveeclipse if you open the console view

i already proposed that it could be shown in Console see https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=288093
But that was rejected and the con sense was to add it in the toolbar with drop down?! 
Strange that this is questioned again.

**Comment by laeubi** [comment]
> But that was rejected and the con sense was to add it in the toolbar with drop down?!

I haven't followed the discussion, but it might be more that there are now *two* terminate buttons (don't know if it is possible to merge these two into one ...)

**Comment by jukzi** [comment]
so how about the new button just get's another icon like the terminate_all_co.png? 
terminate_all_co

**Comment by jukzi** [comment]
What is important to me is that any "terminate all" it is accessible in the java perspective after i have started multiple launches.
So i do not care if it is in the toolbar (always accessible) or console (typically visible after launch).
What i would not like is that i would have to open any hidden view or even change perspective first.
In the toolbar it would be ok for me to have a "close all" in a drop down. but The problem with the current "terminate button" is that it is only visible in the debug perspective.

**Comment by iloveeclipse** [comment]
> The problem with the current "terminate button" is that it is only visible in the debug perspective.

Not for me. I always debug in java perspective, the toolbar shows up automatically there.

**Comment by laeubi** [comment]
I think you can configure additional buttons when customizing the perspective, so maybe one could simply hide it by default and everyone who needs terminate all can just add to what ever perspective?

**Comment by laeubi** [comment]
This repository was merged with https://github.com/eclipse-platform/eclipse.platform if this PR is still relevant please rebase it and push it to the new origin!

**Pull request closed without merging**
