### PR TITLE
Remove content of the repo after merge into platform one

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by akurtakov** [comment]
Continuation of https://github.com/eclipse-platform/eclipse.platform/pull/524

**Comment by iloveeclipse** [comment]
@akurtakov : I assume you wanted to remove all files, but I see only README change in this PR.

**Comment by akurtakov** [comment]
@iloveeclipse Done now, I should really try to multitask less as it starts to get ridiculous.

**Comment by iloveeclipse** [comment]
Thanks Alex.

**Pull request merged**
