### PR TITLE
Contextual launch configs use editor when available

### PR DESCRIPTION
**Pull request by mickaelistria**
Fixes https://github.com/eclipse-platform/eclipse.platform.debug/pull/139

### CODE REVIEW

**Comment by mickaelistria** [comment]
@jukzi This seems to prevent incorrect launch to leak into the editor context-menu (I tried with plain JUnit). Can you please verify it does also fix the case you reported recently?

**Comment by jukzi** [comment]
This correctly adds the method launch:
image
thanks.

**Comment by mickaelistria** [comment]
Thanks for testing.
As this behavior can be interpreted as a regression, let's merge now.

**Comment by Bananeweizen** [comment]
Is that just from editing the screenshots, or should we worry about the jumping alignment of the menu item labels, too?

**Comment by jukzi** [comment]
That is an actual screenshot. the "intend" was intended by @mickaelistria. I agree it looks unusual see
https://github.com/eclipse-platform/eclipse.platform.debug/pull/139#issuecomment-1549009421

**Comment by mickaelistria** [comment]
> should we worry about the jumping alignment of the menu item labels

>  the "intend" was intended

I added the indent as a way to group things, and to hint users that one item is a child, a specialization, of the other. It was the poor man's solution to express that. But if you think there is no need to give that hint to user, then we can just remove the indent; or we may replace it by something else, such as a bullet... but that would be unusual as well, but maybe unusually "fine" instead of unusually "intriguing".

**Comment by jukzi** [comment]
Expandable submenus "{type} Configurations", please?

**Comment by mickaelistria** [comment]
Expandable submenues require 1 more depth of navigation, it would be a submenu of depth 3, it's not a good pattern, worse than visual markers on a flat and short list.

**Comment by Bananeweizen** [comment]
I might be opening a can of worms by saying that the "nesting" might be more obvious writing the labels like this:
JUnit Plugin Test
JUnit Plugin Test: FooClass
JUnit Plugin Test: FooClass.fooMethod
JUnit Test
JUnit Test: FooClass

i.e inverting the type and label part. However, for quickly finding a certain class in between 10 such menu items, the current order is surely better. That's why I would stay with the current labels and NOT use this inverted naming. :)

I would probably leave away the indentation and hope that the icons lead to sufficient grouping, if the sort order is by launch type now.
I would not introduce submenus, as I imagine the number of launch configs being actively used for a certain coding session to be rather small. And if the number is small, the additional nesting brings a lot of overhead, but rather little additional navigation value.

**Comment by jukzi** [comment]
Depth 3 is not unusual like Team/Switch To/{master}. - which also has dynamical changing content:
image
A separator between all types would look ugly. 
Or what about a single separator like.

```
JUnit Plugin Test
JUnit Test
-------
FooClass
FooClass (2)
FooClass (3)
```

(i would skip that type suffix, as typically someone is using a single type per class anyway and if it is a relevant usecase to try different launchers, the user can still add the type name to the config name)

**Comment by Bananeweizen** [comment]
The last one with first generic launches, then separator, then concrete launches. That suggestion looks good to me.
However, I have no clue if I miss other aspects of the complete discussion since I only came with that menu item label alignment after many other changes were already done. :)

**Pull request merged**
