### PR TITLE
Have different overlays for launch icons in quick access #2

### PR DESCRIPTION
**Pull request by Bananeweizen**
Use the icon associated with the launch mode as an overlay on top of the
icon registered for the launch type. That way, run/debug/profile of the
same launch can be distinguished.

The overlay icon in for default resolution is 12 pixels wide. The
typical overlay size of 7 pixels made it unrecognizable. The 2x
resolution overlay is 16 pixels wide.

grafik

### CODE REVIEW

**Comment by mickaelistria** [comment]
Good patch! please merge it as soon as 4.25 is open for business.

**Comment by SarikaSinha** [comment]
Looks good, Do we still need to add new images to the Images repo ?

@mickaelistria Quick Access does not show Profile Menu options, was this intentionally left out?

**Comment by mickaelistria** [comment]
> Looks good, Do we still need to add new images to the Images repo ?

It would be nice to have, but as those are exported from already existing SVG, I don't think it's so important.

> Quick Access does not show Profile Menu options, was this intentionally left out?

No but as I never use it, I simply forgot about it back then.

**Comment by mickaelistria** [comment]
Can you please rebase and bump version of the bundle by the way if it hasn't changed since very fresh 4.24 release?

**Comment by mickaelistria** [comment]
Thank you!

**Comment by Bananeweizen** [comment]
Thanks to whoever took the effort of version bumping. :)

**Pull request merged**
