### PR TITLE
fix #11: ignore unknown mode when calculating label

### LINKED ISSUE #11: Runtime error opening launch group with unknown mode
Have a stored launch config containing a launch group.
Set the mode attribute of one of the contained launches to "foo".
Open the launch config dialog and select the modified launch.

Exception because the mode is used in a lookup for icons.

The above scenario is not that unlikely because foreign plugins may register new modes, and when browsing a stored launch configuration of such a plugin (e.g. in the test data of that plugin) from the Eclipse IDE, then the mode is unknown, although it will be working fine in the runtime launched from this IDE.

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.debug.ui.ILaunchGroup.getLabel()" because "launchGrp" is null
	at org.eclipse.debug.internal.ui.groups.GroupLaunchConfigurationTabGroup.getLabel(GroupLaunchConfigurationTabGroup.java:660)
	at org.eclipse.debug.internal.ui.groups.GroupLaunchConfigurationTabGroup$LabelProvider.getColumnText(GroupLaunchConfigurationTabGroup.java:162)
	at org.eclipse.jface.viewers.TableColumnViewerLabelProvider.update(TableColumnViewerLabelProvider.java:69)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:970)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.doUpdateItem(CheckboxTreeViewer.java:124)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:126)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1048)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:427)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2109)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:864)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:842)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:790)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalInitializeTree(AbstractTreeViewer.java:1610)
	at org.eclipse.jface.viewers.TreeViewer.internalInitializeTree(TreeViewer.java:787)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$1(AbstractTreeViewer.java:1595)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:396)
	at org.eclipse.jface.viewers.AbstractTreeViewer.inputChanged(AbstractTreeViewer.java:1589)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1632)
	at org.eclipse.debug.internal.ui.groups.GroupLaunchConfigurationTabGroup$GroupLaunchTab.initializeFrom(GroupLaunchConfigurationTabGroup.java:505)
```

### PR DESCRIPTION
**Pull request by Bananeweizen**

### CODE REVIEW

**Comment by iloveeclipse** [comment]
The change looks OK for me, thanks.

Would you please amend your commit and change commit message title according to the guidelines "<issue title> #<issue number>"? Also would be nice to have a bit more descriptive commit message.
After updating that, force push to your branch again.

**Comment by akurtakov** [comment]
@Bananeweizen do you plan to do the changes @iloveeclipse requested?

**Comment by Bananeweizen** [comment]
@akurtakov Sorry, I was absent from Github due to high load of normal work for a while. I've updated the commit (I wasn't aware of the contribution guidelines before). Is it really meant to be verbatim "title #issue"? I prefer "title, fixes #issue" way more, since that auto-closes the issue on merge.

**Comment by akurtakov** [comment]
> @akurtakov Sorry, I was absent from Github due to high load of normal work for a while. I've updated the commit (I wasn't aware of the contribution guidelines before). Is it really meant to be verbatim "title #issue"? I prefer "title, fixes #issue" way more, since that auto-closes the issue on merge.

IMHO that's fine.

**Comment by akurtakov** [comment]
@Bananeweizen we are in RC freeze so please resist merging things until next version stream is opened. As this one is quite safe let's keep it but please pay attention to release schedules better for the future.

**Comment by Bananeweizen** [comment]
@akurtakov Sorry. I explicitly looked into the PR checks where it said that it's okay to merge. Are those not working correctly or what did I miss?

**Comment by akurtakov** [comment]
There is no check for that. There is no code freeze now - commits are expected to be approved by PMC or PL for RCs as per https://www.eclipse.org/eclipse/development/plans/freeze_plan_4_24.php . We never had such automation neither on Gerrit nor here and honestly I have no idea whether it's possible as it would either require making Github know about PMC/PLs or have hardcoded lists of the github accounts in these groups which would complicate things significantly. That's why we ask committers to pay attention to the mailing lists. 
P.S. Help in automating more and making it easier for people to notice things is always welcome of course!

**Pull request merged**
