### PR TITLE
Clean-up: Remove unused Require-Bundle entries

### PR DESCRIPTION
**Pull request by HannesWell**
The main motivation was to remove require bundle of
org.eclipse.osgi.services but other unused are removed too.

### CODE REVIEW

**Comment by HannesWell** [comment]
Additionally remove nearly trivial pom.xml files in favor of Tycho pomless. Those poms only contan additional compiler-args to suppress warnings. Lets see if the suppressed once really occur.

**Comment by HannesWell** [comment]
The failure of the API-check was anticipated and should be fixed once https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/352 was submitted and build.

**Comment by Bananeweizen** [comment]
There are some new issues that are no longer suppressed and which make the build fail. You could change the call to the failure scanning at https://github.com/eclipse-platform/eclipse.platform.debug/blob/master/Jenkinsfile#L33 to accept a certain number of issues (see QualityGate in the Warnings NG documentation), or you could filter the current issues using regex patterns at the same place. If you need more details, you can mention me.

**Comment by HannesWell** [comment]
Thanks looking at the failure, but the errors that I can see are only due to the fact that the API-analysis is executed on projects where it should not be executed, but that should be fixed with https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/352.
But I will call you back, if these issues persist after the other PR is available.

**Comment by mickaelistria** [comment]
>  but the errors that I can see are only due to the fact that the API-analysis is executed on projects where it should not be executed

I suggest you separate PRs about Require-Bundle and removing useless pom.

**Comment by HannesWell** [comment]
> > but the errors that I can see are only due to the fact that the API-analysis is executed on projects where it should not be executed
> 
> I suggest you separate PRs about Require-Bundle and removing useless pom.

Done. The removal of trivial poms was moved to https://github.com/eclipse-platform/eclipse.platform.debug/pull/38.

**Comment by HannesWell** [comment]
The last update was just an adjustment of the commit-message, so there is no need to waste build-time for that.

**Pull request merged**
